name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: MetaMask/action-checkout-and-setup@main
        with:
          is-high-risk-environment: false
          cache-node-modules: true

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: MetaMask/action-checkout-and-setup@main
        with:
          is-high-risk-environment: false
      - run: yarn build
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  lint:
    name: Lint
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: MetaMask/action-checkout-and-setup@main
        with:
          is-high-risk-environment: false
      - run: yarn lint
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  test:
    name: Test
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: MetaMask/action-checkout-and-setup@main
        with:
          is-high-risk-environment: false
      - run: yarn test
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  compatibility-test:
    name: Compatibility test
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: MetaMask/action-checkout-and-setup@main
        with:
          is-high-risk-environment: false
      - name: Install dependencies via Yarn
        run: rm yarn.lock && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn
      - run: yarn test
      - name: Restore lockfile
        run: git restore yarn.lock
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
